### ISSUE TITLE
We stand with the people of Afghanistan. fuck you american

### ISSUE THREAD

**Issue by IxaKylin** [tldr-devops/startpack#3]
![image](https://user-images.githubusercontent.com/100996593/162577249-ed352a78-7249-4eff-b40a-eab5b2a939fe.png)

many people killed by american army. the world not need american . armrcian have been destoired many people home, Libya 、Afghanistan 、Iraq。

In 2003, during a presentation to the UN Security Council, Powell laid out US version of the "evidence" that Iraq possessed weapons of mass destruction, which later turned out to be nonexistent. Even in the US, this presentation was controversial. Many wonder why the US resorted to such an inferior means to try to persuade the UN to back its military action against Iraq.

![image](https://user-images.githubusercontent.com/100996593/162577261-61024150-59cd-4f1a-9b4b-8001041db63c.png)
![image](https://user-images.githubusercontent.com/100996593/162577263-046f35ef-ac94-4305-b9e5-619fdd194165.png)

Vietnam War 1961－1975
nato bombing of Yugoslavia
 The volumes of major arms transfers to the Afghan armed forces grew significantly between 2001–2005

**Comment by Friz-zy** [comment]
Dude, I was born in USSR. I know what soviet soldiers did in Afghanistan and in a lot of other countries. I know that Taliban currently doing in Afghanistan. I know what russian soldiers currently doing in Ukraine.

I know the face of marxism and communism - tens and hundreds of millions of tortured and killed people. My family suffered from these regimes. And I personally think that any marxist or communist - this is either an idiot or a future criminal.

So go and find another place for your ideas.
